version: "3.8"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.2
        restart: always
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
            PBF_PATH: /nominatim/data/merged.osm.pbf
            NOMINATIM_PASSWORD: very_secure_password
        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
            - ./osm-maps/data:/nominatim/data
        shm_size: 8gb

volumes:
    nominatim-data:
